version: "3.5"

services:
  go_getter:
    container_name: go_getter
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    working_dir: /go/app
    command: go run server.go
    restart: always